USE [master]
GO
CREATE DATABASE [tecnu]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tecnu', FILENAME = N'/var/opt/mssql/data/tecnu.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tecnu_log', FILENAME = N'/var/opt/mssql/data/tecnu_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO


CREATE TABLE [dbo].[ALUNO](
	[ID] [bigint] NOT NULL,
	[NNALUNO] [nvarchar](500) NOT NULL,
	[NUCPF] [bigint] NOT NULL,
	[DTNASCIMENTO] [datetime] NOT NULL,
	[DSEMAIL] [nvarchar](100) NOT NULL,
	[NUTELEFONE] [bigint] NOT NULL,
	[INFOADS] [nvarchar](4000) NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
);

CREATE TABLE [dbo].[PERIODO](
	[ID] [bigint] NOT NULL,
	[NNPERIODO] [nvarchar](20) NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
);

CREATE TABLE [dbo].[PROFESSOR](
	[ID] [bigint] NOT NULL,
	[NNPROFESSOR] [nvarchar](500) NOT NULL,
	[NUCPF] [bigint] NOT NULL,
	[DTNASCIMENTO] [datetime] NOT NULL,
	[NUTELEFONE] [bigint] NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CLASSE](
	[ID] [bigint] NOT NULL,
	[DTAULA] [datetime] NOT NULL,
	[HORARIO] [datetime] NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
	[SQPROFESSOR] [bigint] NOT NULL,
	[SQPERIODO] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ClasseAlunos](
	[SQCLASSE] [bigint] NOT NULL,
	[SQALUNO] [bigint] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ClasseAlunos]  WITH CHECK ADD  CONSTRAINT [FKF1DD803755F873DB] FOREIGN KEY([SQCLASSE])
REFERENCES [dbo].[CLASSE] ([ID])
GO

ALTER TABLE [dbo].[ClasseAlunos] CHECK CONSTRAINT [FKF1DD803755F873DB]
GO

ALTER TABLE [dbo].[ClasseAlunos]  WITH CHECK ADD  CONSTRAINT [FKF1DD8037C5F378A4] FOREIGN KEY([SQALUNO])
REFERENCES [dbo].[ALUNO] ([ID])
GO

ALTER TABLE [dbo].[ClasseAlunos] CHECK CONSTRAINT [FKF1DD8037C5F378A4]
GO

ALTER TABLE [dbo].[CLASSE]  WITH CHECK ADD  CONSTRAINT [FKPERIODO] FOREIGN KEY([SQPERIODO])
REFERENCES [dbo].[PERIODO] ([ID])
GO

ALTER TABLE [dbo].[CLASSE] CHECK CONSTRAINT [FKPERIODO]
GO

ALTER TABLE [dbo].[CLASSE]  WITH CHECK ADD  CONSTRAINT [FKPROFESSOR] FOREIGN KEY([SQPROFESSOR])
REFERENCES [dbo].[PROFESSOR] ([ID])
GO

ALTER TABLE [dbo].[CLASSE] CHECK CONSTRAINT [FKPROFESSOR]
GO

